extends Node

var roomDimensions = 6

enum ENEMYTYPE{BARRIERENEMY=0, MAGEENEMY=1, WARRIROENEMY=2, NINJAENEMY=3}

enum DIRECTION{LEFT=0, RIGHT=1, UP=2, DOWN=3, MIDDLE=4, RIGHTDOWN = 5, RIGHTUP = 6, LEFTDOWN = 7, LEFTUP = 8}

enum ATTACKTYPE{SWORD = 1, MAGIC = 2, NINJA=3} 
