extends Node

var roomDimensions = 9

enum ENEMYTYPE{BARRIERENEMY=0, MAGEENEMY=1, WARRIROENEMY=2, NINJAENEMY=3}

enum DIRECTION{LEFT=0, RIGHT=1, UP=2, DOWN=3, MIDDLE=4}

enum ATTACKTYPE{SWORD = 1, MAGIC = 2, NINJA=3} 
